from collections import OrderedDict

RAW_FILE_EXTENSIONS = OrderedDict(
    {
        "Hasselblad *.3fr": "3fr",
        "*.ari": "ari",
        "Sony *.arw": "arw",
        "Casio *.bay": "bay",
        "Canon *.crw": "crw",
        "Canon *.cr2": "cr2",
        "Canon *.cr3": "cr3",
        "Phase One *.cap": "cap",
        "*.data": "data",
        "Kodak *.dcs": "dcs",
        "Kodak *.dcr": "dcr",
        "Adobe *.dng": "dng",
        "Kodak *.drf": "drf",
        "Capture One *.eip": "eip",
        "Epson *.erf": "erf",
        "Hasselblad *.fff": "fff",
        "GoPro *.gpr": "gpr",
        "PhaseOne *.iiq": "iiq",
        "JPEG *.jpg": "jpg",
        "Kodak *.k25": "k25",
        "Kodak *.kdc": "kdc",
        "Minolta *.mdc": "mdc",
        "Mamiya *.mef": "mef",
        "Leaf *.mos": "mos",
        "Minolta *.mrw": "mrw",
        "Nikon *.nef": "nef",
        "Nikon *.nrw": "nrw",
        "*.obm": "obm",
        "Olympus *.orf": "orf ",
        "Pentax *.pef": "pef",
        "Pentax *.ptx": "ptx",
        "Logitech *.pxn": "pxn",
        "*.r3d": "r3d",
        "Fuji *.raf": "raf",
        "*.raw": "raw",
        "Leica *.rwl": "rwl",
        "Panasonic *.rw2": "rw2",
        "*.rwz": "rwz",
        "Sony *.sr2": "sr2",
        "Sony *.srf": "srf",
        "Samsung *.srw": "srw",
        "TIFF *.tif": "tif",
        "Sigma *.3xf": "x3f",
    }
)
